### ISSUE TITLE
2.9.64 and 2.9.65 doesn't work

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1610]
both updates do not load, I had to go back to 2.9.63    

WM0I

**Comment by db4ple** [comment]
Hi,
could be explain, what you meant by "did not load", was the boot process not working? Or was it a problem on your side? 

Thanks!
Danilo

**Comment by WM0I** [comment]
2.9.65 loaded but when ran the new firmware all I got on the screen was the upper right portion of a normal screen. Nothing worked. So I tried to reload 2.9.64 which worked before I loaded 2.9.65. Now when loading the 64 version I got an error 2 message at the bottom of the screen and it wouldn't run.  I am now at firmware version 2.9.63 and it works.

WM9I

**Comment by df8oe** [comment]
"Error 2" I have seen some months ago when bootloader was not able to access USB stick. In my case it was a damaged stick. But it is so long ago that I cannot remember what was exactly the text message and where it was placed... Could you please test using another USB stick?

**Comment by WM0I** [comment]
Replace the USB stick and loaded 2.9.65 firmware. I got the same results but with No Error 2 message. When I tried to run the new firmware I get just the upper right hand one 4th of a normal screen. 2.9.64 firmware loads OK now.

WM0I

**Comment by db4ple** [comment]
Hi,
thanks for trying again. Well, seems there is an issue in 2.9.65 With is not entirely unlikely. 
Is the issue already on the boot screen or is boot screen working but the main screen is only partial?

**Comment by WM0I** [comment]
Boot screen seams to be working but the main screen is not. The best I can describe what I see is if you cut the main screen up into 4 sections 2 x 2 . Nothing works and I have to take power off to turn it off. 
WM0I

**Comment by db4ple** [comment]
Ok, yes, description makes enough sense to me. You have a STM32F4 with 512k if I remember correctly. Is that right? Parallel or Serial display, see System Info menu, in case you don't know this.
Thanks.

**Comment by WM0I** [comment]
What I am seeing in system info is HY28B SP1 and 512k.  So I guess I need a newer UI board which is no longer available.
WM0I

**Comment by db4ple** [comment]
Hi,
it is not HY28B SP1 but HY28B SPI -> aka serial display connection. You don't need a new UI board, we need to fix the software. I have an idea what the problem could be. And I also have the hardware to test this idea.  For now, simply stay at 2.9.64 until we release a fix.

**Comment by df8oe** [comment]
I do have a mcHF with SPI-display and it works like a charm with 2.9.65 firmware. It uses STM32F429 MCU...

**Comment by WM0I** [comment]
My CPU is 413h.     

WM0I

**Comment by df8oe** [comment]
Hi Rich,

your MCU is F40x@512KB - the smallest one which is available / will work on mcHF. The number alone is not sufficient for description - the amount of flash must be added. Noone here has access to this MCU. 
But it is nearly impossible that amount of flash is the reason.

**Comment by db4ple** [comment]
Hi,
@df8oe, Rich already gave us the 512k, but like you, I don't think it is the flash size. I have a very different hunch. See my next pull request.

**Comment by df8oe** [comment]
Sorry - accidently closed.

**Comment by df8oe** [comment]
I am exited if 2.9.66 has different behaviour at affected radio...

**Comment by ok1if** [comment]
2.9.64 working normal, but 2.9.65 and 2.9.66 not (512 kB)

**Comment by db4ple** [comment]
@ok1if:  What is happening? Same as @WM0I described, "broken" main screen?
Do you also have an SPI display or is it parallel?

**Comment by UR7FM** [comment]
Same problem with 2.9.65 and 2.9.66
![error2](https://user-images.githubusercontent.com/35993313/48573464-f1ca8800-e914-11e8-8c49-08a47aceb8eb.jpg)

**Comment by db4ple** [comment]
Hi @UR7FM 
thanks a lot for the picture.  Interesting.

**Comment by db4ple** [comment]
@df8oe , should we try to disabled your version check code? Just to see if this makes a difference?
I cannot reproduce the issue although my machine is very close to the one of @WM0I (STM32F407, 192k RAM, SPI display, major difference is 1024k vs. 512k flash).

**Comment by df8oe** [comment]
I have disabled it. If this makes a difference **we must investigate what is going on**. Release 67 will be published in a few seconds

**Comment by df8oe** [comment]
This was my idea too: the problem is sleeping at an unidentified part. Unhappily I am nearly sure we will not find it until we do have access to a machine which shows the issue. I never have had seen such a machine.

**Comment by df8oe** [comment]
Question to all: Does anyone have a MCU > 512KB flash which shows the issue?

**Comment by UR7FM** [comment]
Same problem with 2.9.67 ::(

**Comment by db4ple** [comment]
Could someone of you please do provide us with a dump of the settings using the uhsdr_tool, see 
https://github.com/df8oe/UHSDR/wiki/Backup-and-Restore#backup--restore-on-external-computer-since-2919 and attach the dump here. Maybe it helps us to reproduce the issue.

Thank you!

**Comment by UR7FM** [comment]
Can't start uhsdr tool on my Windows7(32bit)...tried to run from a command prompt window but system not compatable...

**Comment by db4ple** [comment]
Thanks anyway, maybe one of the two other hams have more luck.

**Comment by db4ple** [comment]
@ok1if : Do you have the same screen issue, as UR7FM? If so, would you be willing to send your unit to us in Germany for testing? We are in need of a unit which does have the issue and on which we can use the real-time debugging using a ST-LINK probe. We'd cover the shipping cost, if that is an issue for you.

**Comment by db4ple** [comment]
BTW, the configuration backup is still something I would like to try as well in order to possibly prevent the shipping of a mcHF to us.

**Comment by WM0I** [comment]
Sending my unit tp you so that can resolve this problem is a great idea. My problem with it is that is the only radio I have. I am 74 years old I have very little money to by another one. Do you have unit to replace this one where we could just trade them?  Let me know if this is possible.

WM0I

**Comment by la2fda** [comment]
Hi.
I have been away for a long time now, and was happy to start up my mchf again yesterday.

I have the same problems with version higher than 2.9.63.
Here is my uhsdr_config_json.
[uhsdr_config.json.txt](https://github.com/df8oe/UHSDR/files/2590003/uhsdr_config.json.txt)
Hope you can use it, and just ask if you want me to test anything else.

I see the first object: "version" says "2.9.34"
This is not correct. I was running on 2.9.34 before I started the upgrade. and I have tried all the versions from latest down to 2.9.63 which I am running now. (also when this config dump was done)
The system info firmware menu says: "S2.9.63"

73 LA2FDA

**Comment by df8oe** [comment]
@la2fda : Pse can you tell us what kind of radio you are using and which version (mcHF, China clone e.g.) and also your MCU (and flash size) and your LCD driving method? Many thanks for your settings - we will see if we can reproduce the issue...

**Comment by db4ple** [comment]
Hi @la2fda 
I'll try to see if this breaks my machine (I hope so :-) )

**Comment by db4ple** [comment]
Hi,
the config from la2fda does not bother my machine at all. It works without problems. So the answer must be somewhere in the hardware section.

**Comment by la2fda** [comment]
Hi again. 
I have a couple of mchf's
This one is v.6 from m0nka, but bought used from a ham in UK.

I uploaded images of all the system-info.
![20181116_191025](https://user-images.githubusercontent.com/30241805/48640265-792c0000-e9d6-11e8-848c-208cead01dc9.jpg)
![20181116_191006](https://user-images.githubusercontent.com/30241805/48639749-d1620280-e9d4-11e8-89ec-1c5c30e55153.jpg)
![20181116_185923](https://user-images.githubusercontent.com/30241805/48639750-d1fa9900-e9d4-11e8-8c8e-e09dbf650aa7.jpg)
![20181116_185905](https://user-images.githubusercontent.com/30241805/48639751-d1fa9900-e9d4-11e8-9815-fc1b7f15f0b1.jpg)
![20181116_185834](https://user-images.githubusercontent.com/30241805/48639752-d1fa9900-e9d4-11e8-9617-af6af0f29ba0.jpg)

I also have self build v.4 from m0nka, with 1024k flash, but this one is broken at the moment, so I am not able to compare. Will try to fix it.....

You are doing a great job with this software ! 
73 LA2FDA

**Comment by tomgit12** [comment]
Hi all,
have the same issue with a RS-918 clone.
Normally i don't bother you because i am using a clone.
I don't have the necessary solder skins. :-(

Here are my config, i also had the last issue with power up what was fixed from you with moving some code lines.

![img_20181116_192917](https://user-images.githubusercontent.com/45106343/48640361-c1e3b900-e9d6-11e8-9b67-51f5b61a56f4.jpg)

![img_20181116_192925](https://user-images.githubusercontent.com/45106343/48640372-c90ac700-e9d6-11e8-9800-195218d85c0e.jpg)

[uhsdr_config.json.txt](https://github.com/df8oe/UHSDR/files/2590465/uhsdr_config.json.txt)

Thanks for your work, you are doing a great work with developing the code!
Can provide my unit if it is necessary.

**Comment by db4ple** [comment]
Thanks, guys!
So far we have only 512k machines showing the problem. But it affects parallel and serial displays alike.
My machine is 1024k but I still cannot see how this could make a difference.

**Comment by tomgit12** [comment]
Small idea from my side, but i am not a programmer here so can not say if it could be a problem.:
There is a known prefetch issue with this cpu.
[link](http://www.onarm.com/forum/62262/)

**Comment by db4ple** [comment]
Hi Tom,
you might have found something. I will build some test binaries and attach them here. Let us see if it helps.

**Comment by tomgit12** [comment]
Glad to hear, i can test if you want.
[Some ](http://ds.arm.com/media/resources/db/chip/st/stm32f417/DM00037591.pdf) more informations for you maybe.....

**Comment by db4ple** [comment]
Thanks Tom, I was already looking at this document when your message arrived to waste some time while the compiler is working :-)

**Comment by db4ple** [comment]
This one should crash. If it does, please tell me which led is still on (red and/or green). 
[fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590561/fw-mchf.zip)

**Comment by la2fda** [comment]
> This one should crash. If it does, please tell me which led is still on (red and/or green).
> [fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590561/fw-mchf.zip)

If you have a dfu, I can test at once.

**Comment by db4ple** [comment]
Ok, here we go:
[fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590606/fw-mchf.zip)

**Comment by la2fda** [comment]
> Ok, here we go:
> [fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590606/fw-mchf.zip)

Display and both leds are dark all time with this one.
..... Seems like I have trouble loading the old one now.......

**Comment by tomgit12** [comment]
> This one should crash. If it does, please tell me which led is still on (red and/or green).
> [fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590561/fw-mchf.zip)

nothing happens, no screen no light. only display flashes 1time fast

**Comment by tomgit12** [comment]
> > Ok, here we go:
> > [fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590606/fw-mchf.zip)
> 
> Display and both leds are dark all time with this one.
> ..... Seems like I have trouble loading the old one now.......

Bootloader still available if you press BAND DOWN & POWER for flashing with usb. Did work for me to get back to the running version

**Comment by la2fda** [comment]
> > > Ok, here we go:
> > > [fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590606/fw-mchf.zip)
> > 
> > 
> > Display and both leds are dark all time with this one.
> > ..... Seems like I have trouble loading the old one now.......
> 
> Bootloader still available if you press BAND DOWN & POWER for flashing with usb. Did work for me to get back to the running version

Tnx Tom. I Have to find a USB stick., - Long time since i used USB for this. :-)

**Comment by db4ple** [comment]
Sorry, my fault. Wait until the next one. Power and Band+ should get you DFU, at least it did for me.

**Comment by db4ple** [comment]
This one please:
[fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590657/fw-mchf.zip)

**Comment by tomgit12** [comment]
Running here! 2.9.65

**Comment by db4ple** [comment]
Hi, 
now comes the real interesting one:
[fw-mchf-prefetch.zip](https://github.com/df8oe/UHSDR/files/2590694/fw-mchf-prefetch.zip)

**Comment by tomgit12** [comment]
> Hi,
> now comes the real interesting one:
> [fw-mchf-prefetch.zip](https://github.com/df8oe/UHSDR/files/2590694/fw-mchf-prefetch.zip)

Also running ? Buildtime 20:47 ....

**Comment by db4ple** [comment]
I suspected that this is also running. I will have to do a  small trick now. Will take a few minutes.

**Comment by ok1if** [comment]
I have the same configuration on RS918 like tomgit12 and with 2.9.65 build 20:47:10 working normal
Milan

**Comment by la2fda** [comment]
> Sorry, my fault. Wait until the next one. Power and Band+ should get you DFU, at least it did for me.

No Problem. I am back in business :-)

**Comment by ok1if** [comment]
Of course 512kB

**Comment by ok1if** [comment]
![img_20181116_203952](https://user-images.githubusercontent.com/34418566/48644903-51439900-e9e4-11e8-9c23-dad2dd7b14aa.jpg)

**Comment by ok1if** [comment]
![img_20181116_204014](https://user-images.githubusercontent.com/34418566/48644941-6b7d7700-e9e4-11e8-959d-1de9214afaaf.jpg)

**Comment by ok1if** [comment]
![img_20181116_204034](https://user-images.githubusercontent.com/34418566/48644956-7801cf80-e9e4-11e8-8590-c236d1e6a66e.jpg)

**Comment by db4ple** [comment]
Hi,
this is bin only, but Tom seems to be able to use it:
[fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590754/fw-mchf.zip)

**Comment by tomgit12** [comment]
> Hi,
> this is bin only, but Tom seems to be able to use it:
> [fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2590754/fw-mchf.zip)

Issue happens again, screen is not complete after successfull starting !
Can test tomorrow more versions, have to leave now here.
Thanks for your quick response!

**Comment by db4ple** [comment]
Okay guys,
I will also call it a day now. 
We made some progress, but I still think I need one of the problematic units on my desk. As you can see from my call sign, I am in Germany and a shipping from Europe would be the quickest way to get this done.

**Comment by WM0I** [comment]
I take it you and the others have a good start at solving this problem and don't need my small unit for trouble shooting.. Good luck, I will wait fir the fix.

WM0I

**Comment by ok1if** [comment]
![5](https://user-images.githubusercontent.com/34418566/48645801-011a0600-e9e7-11e8-81ca-76e31fb70fdd.jpg)

**Comment by ok1if** [comment]
Sorry dont working

**Comment by ok1if** [comment]
The last function version

![4](https://user-images.githubusercontent.com/34418566/48646100-0af03900-e9e8-11e8-820c-342adcbfea5f.jpg)

**Comment by df8oe** [comment]
Very sad that "after all these years" of my praying "do not use 512KB MCUs" there are build devices using this MCU... I expected only very old radios which uses this MCU are alive - but all of you do own newer radios :/ But I am nearly sure if we have acess to one of this we (especially db4ple) can fix it. This will give you some more time until again something must be stripped off so that firmware will fit ;) @WM0I :it would be a very wise decision to ship the radio e.g. to Chuck to swap the MCU...

**Comment by WM0I** [comment]
OK, how do I contact chuck? Thanks.

WM0I

**Comment by df8oe** [comment]
Look for WD8BXS in our German discussion board and send him a pm. I am nearly sure he can and will help you. This would be the best and a future proof solution. If you have fitted 427/429/439 with 2MB flash and 256K RAM you do have bleeding edge for mcHF -not possible to fit a more powerful MCU to mcHF (or clones).

**Comment by db4ple** [comment]
Hi Guys,
we just released 2.9.68. Please test and report.

**Comment by tomgit12** [comment]
> Hi Guys,
> we just released 2.9.68. Please test and report.

No, same issue again. Screen only partial ....

**Comment by db4ple** [comment]
Hi Tom,
this is actually kind of good news. Because I now have the right setup to replicate the official builds which break your machines.

**Comment by db4ple** [comment]
Hi,
please flash this one and go to the Systems Info menu. It should display for CPU now something like 413:XXXXh (for me it is 413:1001h). Please publish the number after ":". Don't get too excited, it says it is 2.9.68 and it works on your machine, but this is only because I used Eclipse instead of the official build process. We still haven't found the issue. We now try to identify if all of you have a specific revision of the processor (this is the second number, which was not displayed in older firmwares).

[fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2591782/fw-mchf.zip)

**Comment by tomgit12** [comment]
I have 413:100fh.

Thanks, Tom

**Comment by df8oe** [comment]
100fh ?? hmmmm.... It does not exist....

possible revisions are:
0x1000: Revision A
0x1001: Revision Z
0x1003: Revision Y
0x1007: Revision 1
0x2001: Revision 3

73
Andreas

**Comment by db4ple** [comment]
Hi,
For our amusement, I included the numbering of the 42/43xxx devices in addition to the 40/41xxx. There no clear scheme how STM maps revision ids and revision names A.
Anyway 100f is Rev Y or 4.

Reference Manual says:
This field indicates the revision of the device.
STM32F405xx/07xx and STM32F415xx/17xx devices (device id 0x413):
0x1000 = Revision A
0x1001 = Revision Z
0x1003 = Revision 1
0x1007 = Revision 2
0x100F= Revision Y and 4

STM32F42xxx and STM32F43xxx devices (device id 0x419):
0x1000 = Revision A
0x1003 = Revision Y
0x1007 = Revision 1
0x2001= Revision 3, 4, 5 and B
0x2007= Revision 4, 5 and B

**Comment by db4ple** [comment]
Hi,
please test, this should stop as usual. If it does, tell me which LED are on when it stops.
[fw-mchf-led-faults-all.zip](https://github.com/df8oe/UHSDR/files/2591881/fw-mchf-led-faults-all.zip)

**Comment by tomgit12** [comment]
> Hi,
> please test, this should stop as usual. If it does, tell me which LED are on when it stops.
> [fw-mchf-led-faults-all.zip](https://github.com/df8oe/UHSDR/files/2591881/fw-mchf-led-faults-all.zip)

Starts normally, main screen issue appears and RED (TX) light is on.

**Comment by db4ple** [comment]
Hi Tom,
cool. That means the processor was stopped by an exception (i.e. an internal fault caused by the processor or the program the processor executes).

**Comment by db4ple** [comment]
Hi Tom,
please do the same as before and report led state:
[fw-mchf-led-faults-coded.zip](https://github.com/df8oe/UHSDR/files/2591898/fw-mchf-led-faults-coded.zip)

**Comment by ok1if** [comment]
In my RS918 (512kB0 starting normaly. Red next green  next all LED off and display partial...

**Comment by db4ple** [comment]
Ok, OK1IF, thank you.
Now, please test this one:
[fw-mchf-busfault-ena.zip](https://github.com/df8oe/UHSDR/files/2591935/fw-mchf-busfault-ena.zip)

**Comment by df8oe** [comment]
@ok1if : would you pse test with the binary of the following post what MCU revision you do have: https://github.com/df8oe/UHSDR/issues/1610#issuecomment-439613611

**Comment by db4ple** [comment]
@ok1if : Please don't get confused by our instructions and do test both binaries, thank you.

**Comment by ok1if** [comment]
With binary busfault the same. RED next green (together), next both swich off and next partial display

**Comment by ok1if** [comment]
I have 413:100fH
2.9.67 running OK

**Comment by ok1if** [comment]
fw-mchf-busfault-ena.zip

Is not functioned and unpossible to read 413?:xxxxx

**Comment by la2fda** [comment]
My cpu
413:1007h
LA2FDA

**Comment by ok1if** [comment]
![a](https://user-images.githubusercontent.com/34418566/48663183-96230a80-ea8c-11e8-8b15-e3ef17a140bc.jpg)

**Comment by tomgit12** [comment]
> Hi Tom,
> please do the same as before and report led state:
> [fw-mchf-led-faults-coded.zip](https://github.com/df8oe/UHSDR/files/2591898/fw-mchf-led-faults-coded.zip)

Displayissue, no led is on
thanks

**Comment by tomgit12** [comment]
> Hi Tom,
> please do the same as before and report led state:
> [fw-mchf-led-faults-coded.zip](https://github.com/df8oe/UHSDR/files/2591898/fw-mchf-led-faults-coded.zip)

Also displayissue, no led again.
73

**Comment by tomgit12** [comment]
> Ok, OK1IF, thank you.
> Now, please test this one:
> [fw-mchf-busfault-ena.zip](https://github.com/df8oe/UHSDR/files/2591935/fw-mchf-busfault-ena.zip)

Also displayissue, no led again.
73

**Comment by ok1if** [comment]
Sorry, with fw-mchf-busfault-ena  only partial screen...

**Comment by db4ple** [comment]
Thanks.
What do we know so far: The processor goes into a hard fault state. This can happen for a number of reasons. We know have to identify which exact reason the fault has. I will have to think how to accomplish that without having debugging access.

**Comment by sp9bsl** [comment]
Hi Guys,
Danilo, I was wondering , would the hard fault stack throw some light at the problem? Simple print on the screen the address where it stopped, example [here](https://www.freertos.org/Debugging-Hard-Faults-On-Cortex-M-Microcontrollers.html)

**Comment by db4ple** [comment]
Stack would be of interest, but before that we should identify the hard faults cause, which is hidden in some "registers". 
BTW, thanks for the link. If we get to the point of reading the stack it will help.

**Comment by db4ple** [comment]
Hi, 
please run this. It will report a value via blinking. 
All leds will go off. Green Led only blink = 0, Green and Red together = 1. It will blink 32 times, then a longer pause and the same value repeats.
Please be careful when writing the value down and verify that you got it right.
Thank you.

[fw-mchf-cfsr-blink.zip](https://github.com/df8oe/UHSDR/files/2592132/fw-mchf-cfsr-blink.zip)

@sp9bsl : Display output does not work in case of serial display, due to DMA. Parallel should work but I cannot test it.

**Comment by ok1if** [comment]
Green and Red together 3 times
8
17
23

**Comment by db4ple** [comment]
Thank you, 
we have an "Unaligned Access Fault", the address of the fault has been recorded and also the address of the instruction causing the problem. Very good. 
Now I have to change the code so that we get the two other values as well. We are getting closer!

**Comment by ok8oi** [comment]
Same problem 2.9.68 as UR7FM mentions in his previous post about 2.9.65 and 66. Went back in 2.9.63 in my RS-918 and everything works fine
![20181117_195930](https://user-images.githubusercontent.com/44703227/48665005-b44a3400-eaa7-11e8-9322-6de474b013e6.jpg)

**Comment by db4ple** [comment]
Hi,
now you will have to write down 3 values, you will see the "red led only" blink the number of the value, followed by the value like described before. 
Verify your numbers!

[fw-mchf-cfsr-bfar-pc.zip](https://github.com/df8oe/UHSDR/files/2592179/fw-mchf-cfsr-bfar-pc.zip)

**Comment by ok1if** [comment]
I have video 13MB, Sorry tell me how to send you....

**Comment by ok1if** [comment]
Video is here>
http://leteckaposta.cz/795691357

**Comment by ok1if** [comment]
I regret, but it is quite difficult for my eyes. Video will be better for you.

**Comment by db4ple** [comment]
Ok,
BFAR: 0x0204ffff0
PC:    0x0801272e, this is the code. Further analysis necessary!
```
080126f8 <arm_biquad_cascade_df1_f32>:
 80126f8:       e92d 47f0       stmdb   sp!, {r4, r5, r6, r7, r8, r9, sl, lr}
 80126fc:       e9d0 5601       ldrd    r5, r6, [r0, #4]
 8012700:       ea4f 0c93       mov.w   ip, r3, lsr #2
 8012704:       f003 0e03       and.w   lr, r3, #3
 8012708:       ea4f 180c       mov.w   r8, ip, lsl #4
 801270c:       6807            ldr     r7, [r0, #0]
 801270e:       eb02 0908       add.w   r9, r2, r8
 8012712:       ea4f 0a8e       mov.w   sl, lr, lsl #2
 8012716:       3614            adds    r6, #20
 8012718:       3510            adds    r5, #16
 801271a:       ed56 4a05       vldr    s9, [r6, #-20]  ; 0xffffffec
 801271e:       ed16 4a04       vldr    s8, [r6, #-16]
 8012722:       ed56 3a03       vldr    s7, [r6, #-12]
 8012726:       ed16 3a02       vldr    s6, [r6, #-8]
 801272a:       ed56 2a01       vldr    s5, [r6, #-4]
 801272e:       ed55 5a04       vldr    s11, [r5, #-16]
 8012732:       ed15 5a03       vldr    s10, [r5, #-12]
 8012736:       ed55 7a02       vldr    s15, [r5, #-8]
 801273a:       ed15 7a01       vldr    s14, [r5, #-4]
``

**Comment by ok1if** [comment]
OK I am looking for cooperation HI

**Comment by sp9bsl** [comment]
when function arm_biquad_cascade_df1_f32 is called its first parameter (passed in R0) is a pointer used by  R5 and R6, R5 is increased by 4 and then floating point register S11 is loaded indirect from memory address R5-4 (as a float array), anyway it is a first read with vector from R5, probably out of range of RAM, BFAR points to empty space far after CCM

**Comment by db4ple** [comment]
Hi Slawek,
r5 is the pointer to pState in the arm_biquad_cascade_df1_f32_inst data structure. We have 5 of these (2 Zoom filter, 2 for sound processing, all during RX interrupt; 1 in TxProcessor). It is safe to assume that we are looking at one of the RX instance. 
Something changes the correct original address (I checked in the .elf)  after init to 0x0204fffc (0x0204fff0 was wrong) which is out of range. That must happen between program start and the access to the filter. 
There is no write to pState as far as I can see. I will now post a new binary, which also displays r0 and lr
This will allow us to identify the affected data structure address.

[fw-mchf-cfsr-bfar-pc-r0-lr.zip](https://github.com/df8oe/UHSDR/files/2592347/fw-mchf-cfsr-bfar-pc-r0-lr.zip)

PLEASE TEST AND REPORT the numbers. Or attach a video.

**Comment by ok1if** [comment]
fw-mchf-cfsr-bfar-pc-r0-lr.zip  VIDEO>

http://leteckaposta.cz/430617013

**Comment by db4ple** [comment]
Ok,
pc 0x0801273e (changed, but points to the same assembly as before, so this is expected)
r0 0x200000cc -> IIR_biquad_Zoom_FFT_I (okay, now we have the data structure and now where we came from)
lr 0x00000000 (might not be used)
And here gets it interesting:
bfar: 0x20004fffc -> this value I know, it is one of the values of the bus faults we actually produce on purpose when we check the ram size.  Please note, that I had the BFAR value wrong yesterday. I have no idea how this value ends up in the BFAR, the last bus fault we produce should be 0x20002fffc since we first test 512k (first value) and the 256k (second value) and both should fail and leave their value in the BFAR.

Just for peace of mind, I checked the binary and of course the correct address (0x20000338) is to be found there.
Now comes the 1 million dollar question: What changes this value? And why only in some machines?

**Comment by db4ple** [comment]
Hi,
I need another test:

[fw-mchf-cfsr-bfar-pc-r0-r5.zip](https://github.com/df8oe/UHSDR/files/2592627/fw-mchf-cfsr-bfar-pc-r0-r5.zip)
Thank you!

**Comment by ok1if** [comment]
fw-mchf-cfsr-bfar-pc-r0-r5.zip

http://leteckaposta.cz/357926371

**Comment by db4ple** [comment]
Hm,
r5 (the 5th item) reads 0x20003b49 (which is 0x20003b38 + 17) and is odd (but must be even) hence the unaligned access fault. The correct value would be 0x20003b48 since this is the location of the data of interest plus 16 (the function internally adds 16 to r5, see above). The value comes from 0x2000000d0 and no code should change this location. But obviously some code does.

**Comment by db4ple** [comment]
This might work or show same issue as before:
In case of issue, please send video.

[fw-mchf-cfsr-bfar-pc-r0-r5-reloc256.zip](https://github.com/df8oe/UHSDR/files/2592687/fw-mchf-cfsr-bfar-pc-r0-r5-reloc256.zip)

**Comment by df8oe** [comment]
Again the 1 million dollar question: why different behaviour on different MCUs running the same code? All of my explanation tries end in "impossible because it must occur on every MCU or on no MCU". Absolutely interesting.

**Comment by db4ple** [comment]
Indeed. But at least it is not a mystery error anymore, we have gone at least one step in the right direction. Some piece of code (most likely) increments a specific memory location but not on all machines. 
BTW, I just pushed my current debug code to https://github.com/db4ple/UHSDR/tree/debug_fault

**Comment by ok1if** [comment]
Congratulation to you.
version 2.9.68 now working withou problems HI

**Comment by db4ple** [comment]
Hi, 
this is not the end of the story. I did a nasty trick, to verify one of my ideas. But we still haven not found the issue as such and we even don't know if my idea was correct. 
For those following: What I did was to move the whole RAM allocation by 256 bytes. The memory location we had trouble with was 0x200000d0, which is now no longer used. By moving the whole memory allocation it was not changed in its order. So if the problem is caused by some code which works relative to the memory allocation (most code does), the issue would not have gone away (at least that is what I assume).  So question is now, is the address at location 0x200000d0 now still being changed or not. Would take a few seconds to find out if I had a machine to work with...

The problem is now, that introducing code which does check this might change the whole binary so that we cannot find the issue anymore at this location because is not happening or in a different place.

**Comment by df8oe** [comment]
I do think there is no other way than having direct access to a machine which does have the issue. Because a ST-Link must be connected for live debugging machines which do have debug header pins are preferred.

**Comment by sp9bsl** [comment]
Hi,
indeed interesting... It happens on very beginning, maybe some step by step displaying the content of pointer to pstate after every initial function call, for example 1:value, 2:value, 3:value etc... just a fake debugging :) Also the stack/heap pointer would be interesting.

**Comment by db4ple** [comment]
Well, it is not clear to me if happens at the beginning, thousands of lines of code have been run before we are hit by the issue.

**Comment by df8oe** [comment]
And again: all of my ideas are trapped in "impossible because it does not impact all machines with F40x processor". All do have same amount of RAM, SRAM, same registers - everything identical - only the amount of flash differs and that cannot be the reason for crashing (I do not see what mech can cause this). Possibly we have found a hardware issue in some revisions of F4 MCUs @512KB. Of course it can be approached by peeking and poking in the existing code (bisect...) but having direct acess to such a device will make it much, much easier. And if the reason is not trivial (and I am thinking _it is not trivial_)  time to fix it will be long enough if we can access device. Maybe it is not fixable because we can detemine the part of code but not explain what is happening.

**Comment by db4ple** [comment]
Yes, that it is not happening on all devices is what puzzles me most. 
And I also would like to say, that I will stop working on this issue until someone sends me an affected unit (which I will have to take apart and add the debug port connections, to be clear about this).
If no one does this, the issue will have to remain unfixed unless someone else spends more time to identify the cause. 
You can get in touch with me here or via the german forum (db4ple , https://www.amateurfunk-sulingen.de/forum/index.php#1), send me a personal message there.

**Comment by df8oe** [comment]
You have done great work Danilo. It is very wise and I am glad that your decision is like this. Could you pse mak a PR for the feature "showing CPU revision in System Menu"? @all who are impacted by this issue: many thanks for your help. We have done big steps forward but now we need more than testing... Until we have done that you can test new binaries of course. They may - or may not - work for you. Last time we have had the isue it was enough to move the position of an independent working function to another place - rediculuous and without any explanation - but it was solving the issue for the 512KB machines. By chance...

**Comment by ok8oi** [comment]
Unfortunately, even the 2.9.69 has the same behaviour in my Chinese clone RS-918 - which, to my knowledge, is identical to the mchf. Only the upper right part of the screen is visible as I mentioned in a previous post of mine. Access to an impacted device seems to be the only solution to the problem. Thank you so much for your efforts guys!

**Comment by df8oe** [comment]
We need a radio which shows the issue. No other way. None of our radios does have any issue, and it seems that nobody in our German discussion group does have the issue, too.

EDIT:
Only very old mcHFs and nearly all clones are impacted. McHF changed to 1MB MCU in 2015 (so RS918 is *not* identical to actual mcHF!). Cloners want to save every Cent and fitted 512KB MCU :)

**Comment by WM0I** [comment]
df8oe, again if I sent you my rig/unite to you I would not have anything to use on HF. How do you propose we handle the transfer to you? How long would have to have it? Is their away to trade my rig/unite for the next level up? How much? I want to help but I don't want to be without of a radio either.

Best regards
Richard      WM0I

**Comment by db4ple** [comment]
Hi Guys,
seems I have found someone sending an affected device to me. So all we can do now is to relax and wait for what there is come.
Hope to have some news for you soon.

**Comment by ok1if** [comment]
Super MSG, thank you

**Comment by db4ple** [comment]
Hi Guys,
you will not believe what I found out, but it is true:

- The issue is not at all related to the flash size, that is just coincidence
- It is not related to any specific hardware difference
- The core of the issue is not related to the F4 processor

And we will have a solution soon!
Stay tuned!

**Comment by m-chichikalov** [comment]
This sounds like a trailer for new movie :)

**Comment by sp9bsl** [comment]
Hi Danilo,
interesting...

**Comment by db4ple** [comment]
It is a game against the clock. Literally!

**Comment by db4ple** [comment]
The end is near, do not fear!

**Comment by db4ple** [comment]
While we are all waiting for Travis to do its job, here is the thing:
It was the bootloader! The bootloader? Yes, the bootloader. 
How on earth can the bootloader create such as mess in the firmware and only in some?
When the firmware starts, it first initializes some data area by copying data from the read only memory to the RAM. Once this is done, the last thing to do is to set the interrupt vector table and shortly after the control is passed to the actual firmware main function, which then initializes hardware and turns on interrupts etc.
Now, the bootloader does exactly the same before it then starts the firmware. It also enables interrupts. These interrupts do something, for instance the SysTick interrupt ticks a clock (i.e. counts up a timer in a memory cell). So when does this stop? In our old implementation when the new main code switched to the new vector table. The bootloader interrupts, unfortunately were never turned off. 
And it can happen that a timer tick happens between the bootloaders and switching to the new firmwares interrupt vector table. See it? The bootloader SysTick increments memory cell, unfortunately sometimes after the memory was already initialized with prepared data from the firmware. 
In this particular case the data being changed was a pointer to a float32_t (which was luck, since pointer to a 4 byte data type are never an odd number and cause an fault). 
Only by chance we had that situation and we could find the problem. Might have cause other weird things before.

Solution is straightforward: We disable all interrupts before starting the firmware. We do this in a safe way, we simply reset the processor and then go straight to the firmware, the process basically goes straight from reset to firmware. We do this by checking for a magic number in a special memory location, if it is there, we know we should start the firmware rightaway, otherwise we run through the normal bootloader code.

**Comment by sp9bsl** [comment]
it sounds like dejavu for me... I had similar problem few months ago in F103 project... The total calm down for core before exiting the bootloader and changing the VTOR is a must. Anyway, good job, congratulations!

**Comment by m-chichikalov** [comment]
Good job!

**Comment by DF5LI** [comment]
What an amazing story! The only 512kB chinese clone, i ever had on my bench, was löng ago back to the owner, so I can't help you .  But anyway, you solved the problen, Danilo!  What should we do without you?

**Comment by ok1if** [comment]
![new_bootloader](https://user-images.githubusercontent.com/34418566/48941089-6d7e9300-ef1a-11e8-83a7-ce05f17f2661.jpg)

Congratulation - good job

Milan

**Comment by WM0I** [comment]
FANTASTIC,      Works great. I am going to do some test to see if other small issues have cleared up with this new bootloader.

Great work.

Best regards
Richard    WM0I

**Comment by df8oe** [comment]
Hi Rich,

can you power on with normal press on power button or must you press button for 2 seconds?

**Comment by la2fda** [comment]
Great !
I am now running BL 5.0.0 and FW 2.9.73. Display is normal again.
I have to press power-button for 2 sec to power on. That's fine for me !
Another thing. I have for both of my mchf's struggeled with power off ( sometimes they dont power off after save settings, and I have to take power cable ) Have not seen this yet after fw upgrade.
I have to test this some days to verify.....

And another thing. My m0nka mchf number two have a 1024 flash. Yesterday I saw the same problem on that one to !!

You are the best !
Thanks for a fantastic job you are doing !

**Comment by WM0I** [comment]
It looks normal except for the double white screen flash. I do have to hold it down until the RED transmit led comes on. But that seams to be normal.

But overall it works.
Richard WM0I

**Comment by db4ple** [comment]
I think we can close this issue now.
To all readers: please update your bootloader to 5.0.1. Bootloader 5.0.0 has some issues, it is good for testing but not the final solution. 
 
Please note: We will not support anyone with  older bootloaders and strange issues! Confirm that the issue exists with 5.0.1 or newer and only then do a report on it.

73
Danilo
