### ISSUE TITLE
VFO switching

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#292]
Hi,

if I set VFOA, LSB, and then toggle to VFOB and there turn on CW, CW will remain at the switch back to VFOA. LSB is however displayed in the mode display.

It makes sense if the mode would be preserved when switching the VFO's. You can then use the two VFO's separately for the SSB- and the CW subband.

73, Wolfgang
DL2KI

**Comment by DG9BFC** [comment]
can also be seen in other modes

example .. it would be nice to use am on vfo a and sync am on vfo b ... and switching between sync am and normal am could be done with the vfo a/b button
 (without the need to switch trough other modes)

73 sigi

dg9bfc

**Comment by df8oe** [comment]
fixed.

vy 73
Andreas

**Comment by DG9BFC** [comment]
not fixed right (filter is not changed)

vfo a/b changes mode ... but in the filter box the filter from old 
setting is shown

example you have sync am in vfo a with 4.2 kc

and and in vfo b you have am with 4.6 kc

toggling vfo a/b and the modes change (seen in mode box above mhz digit) 
... but not the filterbox

73

sigi

Am 23.04.2016 um 07:18 schrieb DF8OE:

**Comment by df8oe** [comment]
fixed.

vy 73
Andreas
