### ISSUE TITLE
VFO switching

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#299]
Hi,

the VFO-switching does not seem (CW / SSB) to work clean. Firmware 23.04.2016 15:56:10.
The adjustment of the filter marker below the waterfall / spectrum, according to the filter setting, does not work also.

73, Wolfgang
DL2KI

**Comment by df8oe** [comment]
fixed.

vy 73
Andreas

**Comment by dl2ki** [comment]
Hi, Andreas,

something is still wrong.

If CW is involved, the frequency will be shown in blue.

Example: VFOA = LSB, CW = VFOB
When switching from VFOB on VFOA SSB is incomprehensible. LSB must be set again.

73, Wolfgang
DL2KI

**Comment by df8oe** [comment]
I cannot reproduce here. Everything works fine.Frequency always is in white and modes are changed correctly.

vy 73
Andreas
